name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/St_Johns
          plugin_languages: yes
          plugin_languages_ignored: >-
            ipynb, html, shell
          plugin_repositories_skipped: >-
            DanielPower/pathfinding-demo,
            DanielPower/COMP4303-Assignment-1,
            DanielPower/COMP4303-Assignment-2,
            DanielPower/COMP4303-Assignment-3,
            DanielPower/COMP4303-Assignment-4,
            DanielPower/COMP3100
